language: ruby
sudo: false
rvm:
  - 2.3.3
  - 2.2.6
  - 2.1
  - 2.0
  - 1.9.3
gemfile:
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_3.2.gemfile
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/activerecord_5.0.gemfile
    - rvm: 2.0
      gemfile: gemfiles/activerecord_5.0.gemfile
    - rvm: 2.1
      gemfile: gemfiles/activerecord_5.0.gemfile
